apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: import-tests-go-qdzffjru
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/import-tests-go-qdzffjru:ca17c394c2754cdb413a6bc7434db503213ddf7b
          name: container-image
